"""empty message

Revision ID: 2f59386acd33
Revises: None
Create Date: 2016-06-20 22:32:55.911469

"""

# revision identifiers, used by Alembic.
revision = '2f59386acd33'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ip_address', sa.String(length=15), nullable=True),
                    sa.Column('mac_address', sa.String(length=32), nullable=False),
                    sa.Column('device_type', sa.String(length=125), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text, nullable=True),
                    sa.Column('settings', sa.Text, nullable=True),
                    sa.Column('is_online', sa.Boolean, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('mac_address')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    ### end Alembic commands ###
